<?php
include '../model/ImpactDB.php';
$un =$_POST['un'];
$targetofficial =$_POST['targetofficial'];
$desiredchange = $_POST['desiredchange'];
$ccimpactplan=$_POST['ccimpactplan'];
$impactfollowuphappening=$_POST['impactfollowup'];
$ifnowhynot=$_POST['whynotfollowing'];
$impactprocess=$_POST['impact-process'];
$impactachieved=$_POST['impactachieved'];
$milestone=$_POST['milestone'];
$dateofimpact=$_POST['date-of-impact'];
$timetakenforimpact=$_POST['time-in-weeks'];
$communityscreening=$_POST['CommunityScreeningDone'];
$noofpeoplesawvideo=$_POST['People-shown'];
$detailsofscreening=$_POST['details-of-community-screening'];
$videoshowntoofficials=$_POST['VideoShowntoOfficials'];
$noofofficials=$_POST['officials-shown'];
$detailsofscreeningofficials=$_POST['details-of-officials-screening'];
$collaborations=$_POST['collaboration'];
$noofpeopleinvolved=$_POST['number-of-people-involved'];
$noofpeopleimpacted=$_POST['number-of-people-impacted'];
$noofvillagesimpacted=$_POST['number-of-villages-impacted'];
$videoproductionstatus=$_POST['ImpactVideoProductionStatus'];
$videoreviewed = $_POST['ImpactVideoReviewed'];
$approvepayment = $_POST['ImpactVideoApprovedforPayment'];
$videoapproveddate = $_POST['date-impact-video-approved'];
$videoreviewedby= $_POST['impact-video-reviewed-by'];
$blognotes = $_POST['BlognotesDone'];
$gifttocc = $_POST['impactvideosenttocc'];
$thankyoucard = $_POST['impactthankyou'];
insertAndUpdateImpact($un,$targetofficial,$desiredchange,$ccimpactplan,$impactfollowuphappening,$ifnowhynot,$impactprocess,$impactachieved,$milestone,$dateofimpact,$timetakenforimpact,$communityscreening,$noofpeoplesawvideo,$detailsofscreening,$videoshowntoofficials,$noofofficials,$detailsofscreeningofficials,$collaborations,$noofpeopleinvolved,$noofpeopleimpacted,$noofvillagesimpacted,$videoproductionstatus,$videoreviewed,$approvepayment,$videoapproveddate,$videoreviewedby,$blognotes,$gifttocc,$thankyoucard);
?>
